#1.FINDING LEADING PRODUCT NAME IN THE REGIONS
SELECT PRODUCTS.PRODUCT_NAME,REGIONS.REGION_NAME
FROM PRODUCTS
INNER JOIN REGIONS ON PRODUCTS.PRODUCT_ID=REGIONS.REGION_ID;


#2.LEADING 5 REGIONS AS PER SALES
SELECT REGIONS.REGION_NAME,SALES.TOTAL_SALES_VALUE
FROM REGIONS
JOIN SALES ON REGIONS.REGION_ID=SALES.SALES_ID
ORDER BY TOTAL_SALES_VALUE DESC LIMIT 5;


#3.FINDING OVERALL SALES,NUMBER OF REGIONS AND PRODUCTS 
SELECT 
SUM(SALES.TOTAL_SALES_VALUE) AS OVERALL_SALES,
COUNT(REGIONS.REGION_NAME) AS TOTAL_REGIONS,
COUNT(PRODUCTS.PRODUCT_NAME) AS TOTAL_PRODUCTS
FROM SALES
JOIN REGIONS ON REGIONS.REGION_ID=SALES.REGION_ID
JOIN PRODUCTS ON PRODUCTS.PRODUCT_ID=SALES.PRODUCT_ID;


#4.LOWEST PERFORMING REGIONS AS PER QUANTITY
SELECT PRODUCTS.PRODUCT_NAME,PRODUCTS.PRODUCT_ID,
SUM(SALES.QUANTITY_SOLD) AS QUANTITY_SOLD
FROM SALES
INNER JOIN PRODUCTS ON PRODUCTS.PRODUCT_ID=SALES.SALES_ID
GROUP BY PRODUCTS.PRODUCT_NAME,PRODUCTS.PRODUCT_ID
ORDER BY PRODUCT_NAME ASC LIMIT 3;


#5. FINDING THE DATE OF HIGHEST AMT OF SALES
SELECT SALES_DATE,
TOTAL_SALES_VALUE AS TOTAL_SALE
FROM SALES
GROUP BY SALES_DATE,TOTAL_SALES_VALUE
ORDER BY TOTAL_SALES_VALUE DESC LIMIT 1;


#6.WHICH PRODUCT HAS HIGHEST REVENUE BUT LOW QUANTITY
SELECT PRODUCTS.PRODUCT_NAME,
SUM(SALES.TOTAL_SALES_VALUE) AS TOTAL_REVENUE,
SUM(SALES.QUANTITY_SOLD) AS QUANTITY
FROM SALES
JOIN PRODUCTS ON PRODUCTS.PRODUCT_ID=SALES.PRODUCT_ID
GROUP BY PRODUCTS.PRODUCT_NAME,SALES.QUANTITY_SOLD
ORDER BY PRODUCTS.PRODUCT_NAME DESC,
SALES.QUANTITY_SOLD ASC LIMIT 1;


#7.FIND THE REVENUE PERCENTAGE OF DAIRY CATEGORY
SELECT PRODUCTS.CATEGORY,
(SUM(SALES.TOTAL_SALES_VALUE) * 100) / 
(SELECT SUM(TOTAL_SALES_VALUE) FROM SALES) 
AS DAIRY_REVENUE_PERCENTAGE
FROM PRODUCTS
JOIN SALES ON PRODUCTS.PRODUCT_ID=SALES.SALES_ID
WHERE PRODUCTS.CATEGORY='DAIRY';


#8.CATEGORY WHICH GENERATES HIGHEST REVENUE
SELECT PRODUCTS.CATEGORY,
SALES.TOTAL_SALES_VALUE AS REVENUE
FROM PRODUCTS
JOIN SALES ON PRODUCTS.PRODUCT_ID=SALES.PRODUCT_ID
GROUP BY CATEGORY,REVENUE
ORDER BY TOTAL_SALES_VALUE DESC LIMIT 5;

#9.MAKING THE CHANGES IN THE TABLE USING UPDATE FUNCTION
UPDATE PRODUCTS
JOIN SALES ON PRODUCTS.PRODUCT_ID=SALES.PRODUCT_ID
SET PRODUCTS.CATEGORY ='PROTEIN FOOD'
WHERE TOTAL_SALES_VALUE=38400;

#10 COMBINE THE SALES OF DAIRY AND BEVERAGES
SELECT 
'DAIRY' AS CATEGORY,
SUM(SALES.TOTAL_SALES_VALUE) AS TOTAL_REVENUE
FROM SALES 
JOIN PRODUCTS ON SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID
WHERE PRODUCTS.CATEGORY = 'DAIRY'

UNION ALL

SELECT 
'BEVERAGES' AS CATEGORY,
SUM(SALES.TOTAL_SALES_VALUE) AS TOTAL_REVENUE
FROM SALES 
JOIN PRODUCTS ON SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID
WHERE PRODUCTS.CATEGORY = 'BEVERAGES';










